# Generated by Django 3.2.21 on 2023-09-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('card', models.IntegerField(max_length=16, verbose_name='Card Number')),
                ('pin', models.IntegerField(max_length=4, verbose_name='Card PIN')),
                ('balance', models.IntegerField(default=0, max_length=100, verbose_name='Balance')),
            ],
        ),
        migrations.CreateModel(
            name='Server2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('card', models.IntegerField(max_length=16, verbose_name='Card Number')),
                ('pin', models.IntegerField(max_length=4, verbose_name='Card PIN')),
                ('balance', models.IntegerField(default=0, max_length=100, verbose_name='Balance')),
            ],
        ),
    ]
